server:
  port: 8089
spring:
  application:
    name: run
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.mybatis: DEBUG
    com.OMS.user_service.client: DEBUG