server:
  port: 7777

spring:
  application:
    name: gateWay
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:5555
          predicates:
            - Path=/auth/**
        - id: contest
          uri: http://localhost:1234
          predicates:
            - Path=/contest/**
        - id: practice
          uri: http://localhost:2222
          predicates:
            - Path=/practice/**

auth:
  service:
    url: http://localhost:5555


logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    com.zaxxer.hikari: DEBUG
    org.mybatis: DEBUG
    com.OMS.user_service.client: DEBUG


